### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by Poodolf** [DoctorJohn/swe2018#1]
to-do:
- entkamerafreezen/ refreezen bei nächste frage (X) barriere
- paar mal barriere antwortbox copy pastas (X)
- fragen und antworten (X)
- münzen spawn bei richtiger antwort um highscore zu puschen
- lebensabzug bei falscher antwort (X) (und ausgrauen der antwortbox)
- box explodiert bei falschen antwort, speziel der partikeleffekt dazu (X)
- vllt chance von monsterspawn bei falschen antwort
- exit weiter nach hinten schieben 

optional:
- fragengenerator und zulieferer (X)
- mathe fragen die random generiert werden (X)
- zeitdruck (vllt 30 sekunden antwortszeit, mit einer animation von einer fallenden decke usw)
- sound effects

QoL:
- Hintergrund oder umrandung um den angezeigten text, damit man es auch lesen kann
- schnelleres lauftempo
- wenn es geht flüssigeres spielerlebnis

Bugs:
- wall jump über barrikade

**Comment by DoctorJohn** [comment]
Jeder dieser Punkte sollte ein eingenes Issue sein, sonst gibts hier totales durcheinander und keiner weiß, was schon gelöst wurde.

**Comment by Poodolf** [comment]
das wird son spam lol

**Comment by Poodolf** [comment]
ich add mal nur die noch nicht gelösten issues
