### ISSUE TITLE
[to-do] Portal weiter weg setzten

### ISSUE THREAD

**Issue by Poodolf** [DoctorJohn/swe2018#14]
zurzeit passen nur 4 Fragen auf das Spielfeld.

**Comment by DoctorJohn** [comment]
Das Portal lässt sich nicht versetzen. Man muss einfach das Spielfeld in der conf/mymod.dat vergrößern oder (und das währe die dynamische lösung) das Spielfeld dynamisch, basierend auf der Anzahl an fragen, vergrößern.
